name: CI

on: [push, pull_request]

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install all dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest


# name : test on realtime database

# on:
#   push:
#   pull_request:

# jobs:
#   run-tests:
#     runs-on: ubuntu-20.04


#   steps:
#     - name: Checkout code
#       uses: action/checkout@v2
#     - name: Set up Python
#       uses: action/setup-python@v4
#       with:
#         python-version: ${{matrix.python-version}}
        
    
    
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-]
    #     python-version:
    #       - 3.8



    # name: Test
    # runs-on: ${{matrix.os}}

    # steps: 
    #   - name: Checkout code
    #     uses: action/checkout@v3

    #   - name: Set up Python
    #     uses: action/setup-python@v4
    #     with:
    #       python-version: ${{matrix.python-version}}
    #   - name: Install dependencies
    #     run: python -m pip install pytest .
    #   - name: RunTests
    #     run: pytest