name : test on realtime database

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: test1
        run: echo "yup"
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-]
    #     python-version:
    #       - 3.8



    # name: Test
    # runs-on: ${{matrix.os}}

    # steps: 
    #   - name: Checkout code
    #     uses: action/checkout@v3

    #   - name: Set up Python
    #     uses: action/setup-python@v4
    #     with:
    #       python-version: ${{matrix.python-version}}
    #   - name: Install dependencies
    #     run: python -m pip install pytest .
    #   - name: RunTests
    #     run: pytest